if not game:IsLoaded() then game.Loaded:Wait() end

local Players = game:GetService("Players")
local speaker = Players.LocalPlayer
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local messages = {
	"OMG DEV JUST DROPPED NAVAL WARFARE 2",
	"Guys NAVAL WARFARE 2 just dropped! Join me!",
	"Developer moved to Naval Warfare 2 so he won't fix the exploiters",
	"Naval Warfare 2 has new anti-cheat",
	"Developer made wins transfer over in Naval Warfare 2!!!",
	"NO CHEATERS IN NAVAL WARFARE 2!",
	"Naval Warfare 2 has new models and no exploiters!",
	"This game is never getting fixed. I'm going to play Naval Warfare 2",
	"Developer just dropped Naval Warfare 2",
	"Developer moved to Naval Warfare 2 so he won't fix the exploiters",
	"NAVAL WARFARE 2 LAUNCHED!",
	"Search up 'Naval Warfare 2'",
	"Naval Warfare 2 has way better anti-cheat, no exploiters at all",
	"I'm tired of the exploits, anyone wanna join the newly released Naval Warfare 2? I heard your wins transfer over",
	"I just found this new game called Naval Warfare 2 and it transfers your wins",
	"omg the dev just dropped naval warfare 2",
	"Naval warfare 2 just came out lol",
	"DEV JUST RELEASED NAVAL WARFARE 2",
	"naval warfare 2 just dropped... finally",
	"yo naval warfare 2 is OUT",
	"omg naval warfare 2 is live rn",
	"naval warfare 2 out now go check",
	"dev just launched naval warfare 2",
	"guys naval warfare 2 is out, join me",
	"naval warfare 2 just dropped!!! who's playing",
	"anyone wanna squad up in naval warfare 2",
	"naval warfare 2 dropped, come play",
	"yo who tryna hop on naval warfare 2",
	"come play naval warfare 2 just released",
	"dev moved on to naval warfare 2, no more updates here",
	"he not fixing this anymore, all focus on naval warfare 2",
	"No point waiting, dev only cares about naval warfare 2 now",
	"this game abandoned, dev on naval warfare 2",
	"naval warfare 2 is where dev moved, rip this game",
	"naval warfare 2 got better anti cheat",
	"anti cheat in naval warfare 2 actually works",
	"They fixed the exploits in Naval Warfare 2",
	"Naval Warfare 2 don't have hackers lol. Why are you guys playing this still?",
	"naval warfare 2 patched all the cheats",
	"dev made wins carry over in naval warfare 2",
	"your wins transfer to naval warfare 2 btw",
	"naval warfare 2 lets u keep your wins",
	"progress moves to naval warfare 2",
	"you don't lose wins in naval warfare 2",
	"no exploiters in naval warfare 2",
	"naval warfare 2 is clean, no cheaters",
	"naval warfare 2 finally fixed the hacker problem.",
	"So tired of cheaters, naval warfare 2 has none",
	"naval warfare 2 = no more hackers",
	"naval warfare 2 got new ships and models",
	"better models and no cheaters in naval warfare 2",
	"naval warfare 2 has updated assets and no bugs",
	"this version is broken, naval warfare 2 way cleaner",
	"naval warfare 2 has all the new stuff",
	"this game's dead, switching to naval warfare 2",
	"i'm done here, going to play naval warfare 2",
	"naval warfare 2 is way better than this",
	"no point staying here, naval warfare 2 just works",
	"moving to naval warfare 2, this place is cooked",
	"developer just released naval warfare 2",
	"dev finally dropped naval warfare 2",
	"naval warfare 2 just went public",
	"new naval warfare 2 out now",
	"dev dropped the sequel naval warfare 2",
	"NAVAL WARFARE 2 IS LIVE",
	"naval warfare 2 launched go play",
	"GO go go naval warfare 2 just launched",
	"naval warfare 2 finally here",
	"I am having fun grinding naval warfare 2, please play with me, exploiters ruined this game",
	"Search 'naval warfare 2'",
	"look up naval warfare 2",
	"go find naval warfare 2 in the search",
	"search naval warfare 2 it's out",
	"just type naval warfare 2 you'll see it",
	"naval warfare 2 has way better anti-cheat.",
	"no exploiters anymore in naval warfare 2",
	"naval warfare 2 patched everything.",
	"they cleaned it up in naval warfare 2",
	"Naval warfare 2 has real anti cheat now.",
	"i'm tired of the exploits, switching to naval warfare 2",
	"who wants to try naval warfare 2? it's new and wins carry",
	"done with hackers here, naval warfare 2 fixed all that",
	"Naval warfare 2 just dropped, anyone joining me?",
	"heard wins transfer in naval warfare 2, let's go!!",
	"Just found naval warfare 2 and your stats carry crazy stuff",
	"naval warfare 2 is new and it keeps your wins",
	"Wins transfer in naval warfare 2, no reset.",
	"Naval warfare 2 lets u keep everything",
	"Check out naval warfare 2, same dev, wins move",
	"NAVAL WARFARE 2 JUST DROPPED",
	"yo DEV finally dropped NAVAL WARFARE 2",
	"naval warfare 2 just got released LET'S GOOO",
	"dev dropped naval warfare 2 it's live rn",
	"NAVAL WARFARE 2 OUT NOW GO PLAY",
	"naval warfare 2 just came out what",
	"OMG bro naval warfare 2 is HERE",
	"yo why nobody talkin abt naval warfare 2 its OUT",
	"naval warfare 2 just dropped, someone hop on",
	"WHO'S PLAYING NAVAL WARFARE 2 RN??",
	"i'm on naval warfare 2 now, join if u tired of hackers",
	"naval warfare 2 just released, come try it",
	"bro naval warfare 2 has no hackers finally",
	"tired of all the exploiting here, imma play naval warfare 2",
	"Naval warfare 2 is hacker-free, thank god,",
	"naval warfare 2 got NEW models and ships",
	"Better looking game and no exploiters in naval warfare 2",
	"NW2 has updated graphics and less bugs",
	"naval warfare 2 = clean, updated, no cheaters",
	"graphics are better and no hackers? naval warfare 2 win",
	"I'm done with this game, playing naval warfare 2",
	"naval warfare 2 way smoother, this game laggy af",
	"Why stay here when naval warfare 2 is out",
	"Nw2 fixed everything this one didn't",
	"this game is over, naval warfare 2 got next",
	"DEVELOPER RELEASED NAVAL WARFARE 2",
	"naval warfare 2 is LIVE",
	"go play naval warfare 2 rn it's out",
	"yo naval warfare 2 is officially launched",
	"DEV DROPPED NAVAL WARFARE 2",
	"Search up 'Naval Warfare 2' and you'll find it.",
	"type in naval warfare 2 it's there",
	"Look up the sequel naval warfare 2.",
	"Just search naval warfare 2 it dropped just now",
	"NAVAL WARFARE 2 in search bar rn",
	"Naval warfare 2 fixed the anti cheat",
	"no more exploiters in naval warfare 2!",
	"naval warfare 2 got a whole new system",
	"Naval Warfare 2 cracked down on cheaters.",
	"naval warfare 2 ain't got no script kiddies",
	"yo i'm switching to naval warfare 2 who's coming",
	"Anyone else hopping on nw2?",
	"naval warfare 2 just released and wins carry",
	"so done with this game, naval warfare 2 better",
	"naval warfare 2 out now, who's joining me ?",
	"just played naval warfare 2 and my wins transferred",
	"New game naval warfare 2 and u keep ur progress",
	"found naval warfare 2 and it actually works",
	"Naval warfare 2 lets u bring over ur stats",
	"Wins transfer in nw2 :)",
	"Dang this game got overrun by exploiters, imma go play naval warfare 2",
	"This game used to be fun, imma look for a new naval warfare game",
	"Every server i join there are exploiters, imma try the new one"
}

local function contains(list, str)return table.find(list, str) ~= nil end


local status, err = pcall(function()
	local data = {}
	for _, p in pairs(Players:GetPlayers()) do
		local l = p:FindFirstChild("leaderstats")
		data[p.Name]={l.Score.Value,l.Win.Value,l.Coin.Value,p.Team.Name,p.DisplayName,p.UserId}
	end

	request({Url="https://server.blitzmarine.com/api/update?&bot="..speaker.Name,Method="POST",Body=game:GetService("HttpService"):JSONEncode({id=game.JobId,players=data,islands={},japan=1,usa=1,vehicles={},time=1}),Headers={["Content-Type"]="application/json"}})
	ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(messages[math.random(#messages)], "All")
end)

while task.wait(.1) do
	local status, err = pcall(function() 
		local r=request({Url="https://server.blitzmarine.com/?bot=yes",Method="GET"})
		local d=game:GetService("HttpService"):JSONDecode(r.Body)
		game:GetService("TeleportService"):TeleportToPlaceInstance(game.PlaceId,d[1].id,speaker)
	end)
end
